[[FastTree]]
arch = "aarch64"
git-tree-sha1 = "58dd0d7eb7c3d23456901c42edbaca20bee13ed2"
os = "macos"

    [[FastTree.download]]
    sha256 = "3c530fc929dc870a91516f961070e56079146d69d1dd8f458ada37731a8db06f"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.aarch64-apple-darwin.tar.gz"
[[FastTree]]
arch = "aarch64"
git-tree-sha1 = "c5fdfc1ec3c50a7b71d4e7f3a999dbab5340fb94"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "5042b3ed176e9a3d2e1a06e01a6aaf94eacf4afb87170ad441d189383e1bbfd3"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.aarch64-linux-gnu.tar.gz"
[[FastTree]]
arch = "aarch64"
git-tree-sha1 = "54ea413411e6eea358f82788b09d498b5f2784fa"
libc = "musl"
os = "linux"

    [[FastTree.download]]
    sha256 = "3145d4292119f24de3e8479dea497d0ce0fc64103e168207764c6fc34a6ac8ae"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.aarch64-linux-musl.tar.gz"
[[FastTree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5c3ebe595720870b090b22b4d1be1b2995ae8ff"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "786d1fdd7daf6b9dfeaa1c482fef9ad0ab8414e8c2922da76940b49e7d27fbc3"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.armv6l-linux-gnueabihf.tar.gz"
[[FastTree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e83a799a84a3101dcb01ec7a72d95091d11112d5"
libc = "musl"
os = "linux"

    [[FastTree.download]]
    sha256 = "7f7c8818b102556d4fb15c2bb3f60f27479db819a66eacf1fe292c19886db5f9"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.armv6l-linux-musleabihf.tar.gz"
[[FastTree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3677dc236a3ece34a226971ae4e8499fd190e4da"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "d464d7c3e50c4726637ef88ab847c9840a8b3d3e0abfa865cbaecf69aec2314a"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.armv7l-linux-gnueabihf.tar.gz"
[[FastTree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e45b1a2e914209a2d9fe1b1881d7d24960ea67ed"
libc = "musl"
os = "linux"

    [[FastTree.download]]
    sha256 = "2c24eb97884f1327a586387fb44675ffce9ecfd6953da2d0e792a24347155063"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.armv7l-linux-musleabihf.tar.gz"
[[FastTree]]
arch = "i686"
git-tree-sha1 = "6f56f569ece76a452b0eeea2143d378a6b031206"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "d8e610d6a139b8a05de912fe53f5a301803b5488fec91119d42b3c2d123b60e3"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.i686-linux-gnu.tar.gz"
[[FastTree]]
arch = "i686"
git-tree-sha1 = "4b79853b6889100d94533675060f92208b9dde5b"
libc = "musl"
os = "linux"

    [[FastTree.download]]
    sha256 = "86eb724b2d31dc0d106cfd9211f9a4fdf6c35622c37c0c57389eb2305e7f9a2c"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.i686-linux-musl.tar.gz"
[[FastTree]]
arch = "i686"
git-tree-sha1 = "b1e4ce95d20c0a0c00ab4aa76d043909f811ec6c"
os = "windows"

    [[FastTree.download]]
    sha256 = "a73608e3346770682523913fd00590a00c148c81c4c7c12b1f901b55d34ce036"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.i686-w64-mingw32.tar.gz"
[[FastTree]]
arch = "powerpc64le"
git-tree-sha1 = "56162e9a4a78796c445868a1edd5ee8f2fbabede"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "99f4169de4255273339ddf90efa965f5f7fb7bd6a9f325f21d8b567a3553317d"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.powerpc64le-linux-gnu.tar.gz"
[[FastTree]]
arch = "x86_64"
git-tree-sha1 = "25b1f13bf59219980cf9251dd92c948fb66982ff"
os = "macos"

    [[FastTree.download]]
    sha256 = "a387976024c7a33ed31c68d39ba877696a1c4643ba14dbc4d2538af8c3bbccab"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.x86_64-apple-darwin.tar.gz"
[[FastTree]]
arch = "x86_64"
git-tree-sha1 = "c70d9209a7f9716a85c56234c246205e6de6fd49"
libc = "glibc"
os = "linux"

    [[FastTree.download]]
    sha256 = "c9bc9fe6cb742716a611d0df18374c30e0b7e22667eee68524767a44df196c80"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.x86_64-linux-gnu.tar.gz"
[[FastTree]]
arch = "x86_64"
git-tree-sha1 = "c8dd82d22500fd38770c27428645746687370afa"
libc = "musl"
os = "linux"

    [[FastTree.download]]
    sha256 = "9e89cf0845a11026fcafa911446b54365da78cb9e46db492ba387387131a205c"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.x86_64-linux-musl.tar.gz"
[[FastTree]]
arch = "x86_64"
git-tree-sha1 = "9ddda5b14d08bde4f35cae88c0a19bc062cf3e37"
os = "freebsd"

    [[FastTree.download]]
    sha256 = "4a3db288a8e109617bafc63b92ed73def3c1a5d05052f38800221d2dfcb1cc60"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.x86_64-unknown-freebsd.tar.gz"
[[FastTree]]
arch = "x86_64"
git-tree-sha1 = "b07e5b98a6de26b14d14562a68bc6c61d5193cc6"
os = "windows"

    [[FastTree.download]]
    sha256 = "61b90d77c1aef0e357c8ad217c709627935eed1d6a6e4f92aac740e6767ece51"
    url = "https://github.com/JuliaBinaryWrappers/FastTree_jll.jl/releases/download/FastTree-v2.1.11+1/FastTree.v2.1.11.x86_64-w64-mingw32.tar.gz"
